; Script generated by ChatGPT for Inno Setup installer for BookStoreApp

[Setup]
AppName=BookStoreApp
AppVersion=1.0
DefaultDirName={pf}\BookStoreApp
DefaultGroupName=BookStoreApp
OutputBaseFilename=BookStoreAppInstaller
Compression=lzma
SolidCompression=yes

[Files]
; Main executable
Source: "dist\\main.exe"; DestDir: "{app}"; Flags: ignoreversion
; Database file
Source: "books.db"; DestDir: "{app}"; Flags: ignoreversion
; Icons folder and contents
Source: "icons\\*"; DestDir: "{app}\\icons"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\\BookStoreApp"; Filename: "{app}\\main.exe"
Name: "{commondesktop}\\BookStoreApp"; Filename: "{app}\\main.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Создать значок на рабочем столе"; GroupDescription: "Дополнительно:"; Flags: unchecked
